sudo: false
language: python
cache: pip
python:
- '3.6'
before_install:
    - travis_retry pip install twine
install:
    - travis_retry pip install -r requirements.txt
    - travis_retry pip install -r test-requirements.txt
script:
    - FLASK_APP=app.app py.test
    - flake8
